Repository VeryOpenSource/uome2_client, pull requests merged in 2022-03, with the labels that each got.

#4 Add open source license
  LICENSE
Labels: enhancement

#5 Add static analysis
  analysis_options.yaml
  android/build.gradle
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#7 Add PR check
  .github/workflows/dev_pr_check.yml
Labels: enhancement

#9 Dummy PR
  .github/workflows/dev_pr_check.yml
  .vscode/settings.json
  lib/main.dart
  pubspec.lock
Labels: CI/CD

#11 Add project structure
  .gitignore
  lib/core/error/exceptions.dart
  lib/core/error/failures.dart
  lib/core/network/network_info.dart
  lib/features/auth/data/datasources/auth_datasource.dart
  lib/features/auth/data/models/auth_model.dart
  lib/features/auth/data/repositories/auth_repository.dart
  lib/features/auth/presentation/bloc/auth/auth_bloc.dart
  lib/features/auth/presentation/bloc/auth/auth_event.dart
  lib/features/auth/presentation/bloc/auth/auth_state.dart
  lib/features/auth/presentation/pages/login_page.dart
  lib/features/auth/presentation/widgets/custom_button.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#16 App theme
  lib/core/theme/colors.dart
  lib/core/theme/text_style.dart
  lib/core/theme/theme.dart
  lib/features/auth/presentation/pages/login_page.dart
  lib/features/auth/presentation/widgets/custom_button.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#17 Correct App theme
  lib/core/themes/app_colors.dart
  lib/core/themes/app_text_style.dart
  lib/core/themes/app_theme.dart
  lib/core/themes/themes.dart
  lib/features/auth/data/datasources/data_sources.dart
  lib/features/auth/data/models/models.dart
  lib/features/auth/data/repositories/repositories.dart
  lib/features/auth/presentation/bloc/auth/auth_bloc.dart
  lib/features/auth/presentation/bloc/auth/auth_event.dart
  lib/features/auth/presentation/cubit/auth_cubit.dart
  lib/features/auth/presentation/cubit/auth_state.dart
  lib/features/auth/presentation/pages/login_page.dart
  lib/features/auth/presentation/pages/pages.dart
  lib/features/auth/presentation/widgets/custom_button.dart
  lib/features/auth/presentation/widgets/widgets.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: duplicate, enhancement
